# Generated by Django 3.1.4 on 2021-08-25 19:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_reg_number', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
                ('destination', models.TextField()),
                ('purpose', models.TextField()),
                ('trip_date', models.DateField(auto_now_add=True)),
                ('passengers', models.IntegerField(blank=True, null=True)),
                ('time_in', models.DateTimeField(null=True)),
                ('time_out', models.DateTimeField(default=datetime.datetime(2021, 8, 25, 21, 7, 17, 885651))),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TripInstance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.RESTRICT, to='home.trip')),
            ],
        ),
    ]
