# Generated by Django 3.1.4 on 2021-08-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
