# Generated by Django 3.2.8 on 2021-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210825_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='time_out',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_date',
        ),
        migrations.AlterField(
            model_name='officer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
