# Generated by Django 3.2.8 on 2021-10-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211026_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='car_reg_number',
        ),
    ]
